version: '2'

volumes:
  postgres-data:
    driver: local

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: P4Ssw0rD!

  app: &base
    image: theclowder/schemata:latest
    working_dir: /go/src/github.com/root/
    volumes:
      - .:/go/src/github.com/root/
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:P4Ssw0rD!@db:5432/db_dev?sslmode=disable
    ports:
      - 80:80
    command: go run main.go

  test:
    <<: *base
    command: goconvey -host=0.0.0.0
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:P4Ssw0rD!@db:5432/db_test?sslmode=disable
